### ISSUE TITLE
Website resizer

### ISSUE THREAD

**Issue by niallobrien** [groundworkcss/groundwork#272]
Hi, I'm just wondering what library are you using to change the screen dimensions for the different device sizes at the top of the homepage?

Thanks in advance.

**Comment by ghepting** [comment]
No library, I created that myself. Check out my stand alone version here:
http://ghepting.github.io/resizer/


On Sunday, July 19, 2015, niallobrien <notifications@github.com> wrote:

> Hi, I'm just wondering what library are you using to change the screen
> dimensions for the different device sizes at the top of the homepage?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groundworkcss/groundwork/issues/272>.
>


-- 
 - Gary Hepting
   ghepting@gmail.com

**Comment by niallobrien** [comment]
Awesome, thank you.
