### ISSUE TITLE
Firefox - abbr tag - multiple underlines

### ISSUE THREAD

**Issue by Scheirle** [groundworkcss/groundwork#274]
Since a few weeks the `<abbr>` Tag gets underlined multiple times in Firefox.
Once from the groundwork css file.
And (I assume) the other time from the firefox render engine.

Example Site with `<abbr>` Tags: [jsfiddle.net](http://jsfiddle.net/34xtqs68/)

In Chromium only the groundwork underline is visible.

**Comment by Scheirle** [comment]
Probably related: https://www.fxsitecompat.com/en-US/docs/2015/default-style-of-abbr-acronym-has-been-changed/

**Comment by ghepting** [comment]
Ah, I was always skeptical about adding those styles... Pull request welcome! I'd recommending that we just remove the styles at this point...
