### ISSUE TITLE
jquery-3.1.1 : Object doesn't support property or method 'indexOf'

### ISSUE THREAD

**Issue by smust** [groundworkcss/groundwork#281]
I got below error. I think its caused by $(window).load(function() { ... });

Unhandled exception at line 4, column 19058 in http://localhost:19211/Scripts/jquery-3.1.1.min.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'indexOf'

**Comment by smust** [comment]
worked after changing   $(window).load(function() { ... }); to $(window).on('load', function() { ... });

**Comment by ghepting** [comment]
jquery 3 is not a part of this repository. If you want to make a pull request to add support for jquery 3 (and backward compatibility for 2.x) then please do so!
